[package]
name        = "mondrian-assets"
version.workspace    = true
edition.workspace    = true
authors.workspace    = true
license.workspace    = true

[dependencies]
mondrian-core = { workspace = true }
mondrian-storage = { workspace = true }

serde      = { workspace = true }
serde_json = { workspace = true }
uuid       = { workspace = true }
chrono     = { workspace = true }
thiserror  = { workspace = true }
anyhow     = { workspace = true }
tracing    = { workspace = true }
parking_lot = { workspace = true }

# SQLite
rusqlite   = { version = "0.31", features = ["bundled", "backup"] }

[dev-dependencies]
tempfile = { workspace = true }
