[package]
name        = "mondrian-ui-widgets"
version.workspace    = true
edition.workspace    = true
authors.workspace    = true
license.workspace    = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
mondrian-core         = { workspace = true }
mondrian-ui-core      = { workspace = true }
mondrian-ui-layout    = { workspace = true }
mondrian-ui-theme     = { workspace = true }
mondrian-ui-text      = { workspace = true }
mondrian-editor-state = { workspace = true }
mondrian-platform     = { workspace = true }

glam = { workspace = true }
lyon = { workspace = true }
roxmltree = { workspace = true }
svgtypes = { workspace = true }
unicode-segmentation = { workspace = true }
