edition = "2021"

max_width            = 100
hard_tabs            = false
tab_spaces           = 4
newline_style        = "Unix"

# 导入排序
imports_granularity  = "Crate"
group_imports        = "StdExternalCrate"

# 函数参数
fn_params_layout     = "Tall"

# 注释
comment_width        = 100
wrap_comments        = true

# 链式调用
chain_width          = 80

# 结构体
struct_lit_width     = 50
