[package]
name        = "mondrian-platform"
version.workspace    = true
edition.workspace    = true
authors.workspace    = true
license.workspace    = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
mondrian-core          = { workspace = true }
mondrian-platform-core = { workspace = true }
arboard                = { workspace = true }
rfd                    = "0.15"
xcap                   = { workspace = true }
windows-sys            = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies]
objc2                   = "0.6.4"
objc2-app-kit           = { version = "0.3.2", default-features = false, features = ["std", "NSScreen", "objc2-core-foundation", "objc2-core-graphics"] }
objc2-core-foundation   = { version = "0.3.2", default-features = false, features = ["std", "CFData"] }
objc2-core-graphics     = { version = "0.3.2", default-features = false, features = ["std", "CGColorSpace", "CGDirectDisplay", "CGDisplayConfiguration"] }

[target.'cfg(target_os = "linux")'.dependencies]
wayland-client          = { version = "0.31.14", features = ["dlopen"] }
wayland-protocols       = { version = "0.32.12", features = ["client", "staging", "unstable"] }
x11rb                   = { version = "0.13.2", features = ["randr"] }
