[package]
name        = "mondrian-platform"
version.workspace    = true
edition.workspace    = true
authors.workspace    = true
license.workspace    = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
mondrian-core = { workspace = true }
arboard       = { workspace = true }
rfd           = "0.15"
xcap          = { workspace = true }
windows-sys   = { workspace = true }
