[package]
name        = "mondrian-ui-tooltip"
version.workspace    = true
edition.workspace    = true
authors.workspace    = true
license.workspace    = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
mondrian-core         = { workspace = true }
mondrian-ui-core      = { workspace = true }
mondrian-ui-theme     = { workspace = true }

glam = { workspace = true }
