[package]
name        = "mondrian-editor-ui"
version.workspace    = true
edition.workspace    = true
authors.workspace    = true
license.workspace    = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
mondrian-core         = { workspace = true }
mondrian-editor-state = { workspace = true }
mondrian-ui-core      = { workspace = true }
mondrian-ui-theme     = { workspace = true }
mondrian-platform     = { workspace = true }

serde       = { workspace = true }
serde_json  = { workspace = true }
uuid        = { workspace = true }
parking_lot = { workspace = true }
