[package]
name        = "mondrian-ui-renderer"
version.workspace    = true
edition.workspace    = true
authors.workspace    = true
license.workspace    = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
mondrian-core     = { workspace = true }
mondrian-ui-core  = { workspace = true }
mondrian-ui-theme = { workspace = true }

wgpu    = { workspace = true }
glam    = { workspace = true }
bytemuck = { workspace = true }
parking_lot = { workspace = true }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
naga = { workspace = true }
pollster = "0.4"

[[bench]]
name = "renderer_pipeline"
harness = false
