[package]
name        = "mondrian-export"
version.workspace    = true
edition.workspace    = true
authors.workspace    = true
license.workspace    = true

[dependencies]
mondrian-core     = { workspace = true }
mondrian-media    = { workspace = true }
mondrian-timeline = { workspace = true }
mondrian-renderer = { workspace = true }
mondrian-effects  = { workspace = true }
wgpu             = { workspace = true }

tokio       = { workspace = true }
async-trait = { workspace = true }
serde       = { workspace = true }
serde_json  = { workspace = true }
thiserror   = { workspace = true }
tracing     = { workspace = true }
uuid        = { workspace = true }
chrono      = { workspace = true }
parking_lot = { workspace = true }
