[package]
name        = "mondrian-ui-theme"
version.workspace    = true
edition.workspace    = true
authors.workspace    = true
license.workspace    = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
mondrian-core = { workspace = true }

serde   = { workspace = true }
parking_lot = { workspace = true }
