[package]
name        = "mondrian-ui-core"
version.workspace    = true
edition.workspace    = true
authors.workspace    = true
license.workspace    = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
mondrian-core         = { workspace = true }
mondrian-editor-state = { workspace = true }
mondrian-ui-theme     = { workspace = true }
mondrian-platform     = { workspace = true }

uuid    = { workspace = true }
glam    = { workspace = true }
