[package]
name        = "mondrian-core"
version.workspace    = true
edition.workspace    = true
authors.workspace    = true
license.workspace    = true

[dependencies]
# 序列化
serde      = { workspace = true }
serde_json = { workspace = true }
sha2       = { workspace = true }
# ID
uuid       = { workspace = true }
# 时间
chrono     = { workspace = true }
# 错误
thiserror  = { workspace = true }
anyhow     = { workspace = true }
# 日志
tracing    = { workspace = true }
# 并发
crossbeam-channel = { workspace = true }
parking_lot       = { workspace = true }
dashmap           = { workspace = true }
lru               = "0.16"
# 数学
glam       = { workspace = true }
# 颜色管理
ocio-rs    = { workspace = true }
icc-profile = "0.0.3"
moxcms = "0.7.11"

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, features = ["Win32_Storage_FileSystem"] }

[dev-dependencies]
proptest   = "1"
tempfile   = { workspace = true }
