[package]
name        = "mondrian-timeline"
version.workspace    = true
edition.workspace    = true
authors.workspace    = true
license.workspace    = true

[dependencies]
mondrian-core = { workspace = true }

serde      = { workspace = true }
serde_json = { workspace = true }
thiserror  = { workspace = true }
anyhow     = { workspace = true }
tracing    = { workspace = true }
uuid       = { workspace = true }
glam       = { workspace = true }

[dev-dependencies]
mondrian-effects = { workspace = true }
proptest  = "1"
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "visual_schedule"
harness = false
