[package]
name        = "mondrian-ai"
version.workspace    = true
edition.workspace    = true
authors.workspace    = true
license.workspace    = true

[dependencies]
mondrian-core   = { workspace = true }
# 异步
tokio       = { workspace = true }
async-trait = { workspace = true }
# 序列化
serde       = { workspace = true }
serde_json  = { workspace = true }
# 日志
tracing     = { workspace = true }
# YAML 工作流定义
serde_yaml  = "0.9"
